#!/usr/bin/php -q
<?php

function remoteFile($url, $cacheexpires=0) {
	
	$ch = curl_init($url);
	curl_setopt($ch, CURLOPT_HEADER, 0);
	curl_setopt($ch, CURLOPT_USERAGENT, "User-Agent: twitstream/1.0");
	curl_setopt($ch, CURLOPT_FOLLOWLOCATION, TRUE);
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 5);
	$output = curl_exec($ch);
	curl_close($ch);
		
	return($output);
}

function twitterSearch($q, $tweettable, $usertable="", $repliestable="") {

	$url = "http://search.twitter.com/search.json?rpp=100&q=" . urlencode($q);
	$json = json_decode(remoteFile($url), true);
	$r = array(); $rr = array();
	if(is_array($json)) {
		if(array_key_exists("results", $json)) {
			$rr = $json['results'];
		}
	}

	foreach($rr as $tweet){

		$item = array();

		$ds = $tweet['created_at'];
		$dt = strtotime($ds);

		$item['id'] = $tweet['id'];
		$item['date'] = $dt;
		$item['text'] = $tweet['text'];
		$item['user'] = $tweet['from_user'];
		$item['image'] = $tweet['profile_image_url_https'];
		$item['name'] = $tweet['from_user_name'];
		$item['userid'] = $tweet['from_user_id'];

		$query = "insert ignore into " . $tweettable . " (ID, User, UserID, Date, Message) values ('" . mysql_real_escape_string($item['id']) . "', '" . mysql_real_escape_string($item['user']) . "', '" . mysql_real_escape_string($item['userid']) . "', FROM_UNIXTIME(" . $dt . "), '" . mysql_real_escape_string($item['text']) . "');";
		mysql_query($query);

		if(strlen($usertable) > 0) {
			if(array_key_exists("from_user_id", $tweet)) {
				$user_id = $tweet['from_user_id'];
				$user_username = $tweet['from_user'];
				$user_name = $tweet['from_user_name'];
				$user_image = $tweet['profile_image_url_https'];
				$query = "insert into " . $usertable . " (ID, Username, Name, Image) values ('" . mysql_real_escape_string($user_id) . "', '" . mysql_real_escape_string($user_username) . "', '" . mysql_real_escape_string($user_name) . "', '" . mysql_real_escape_string($user_image) . "');";
				mysql_query($query);
			}
		}

		if(strlen($repliestable) > 0) {
			if(array_key_exists("in_reply_to_status_id", $tweet)) {
				$item['parent'] = $tweet['in_reply_to_status_id'];
				$query = "insert ignore into " . $repliestable . " (Child, Parent) values ('" . mysql_real_escape_string($item['id']) . "', '" . mysql_real_escape_string($item['parent']) . "');";
				mysql_query($query);
			}
		}

		$r[] = $item;
	}

	return($r);
}

$configfile = realpath(dirname(__FILE__)) . "/settings.json";
if(!(file_exists($configfile))) {
	fwrite(STDERR, "Error: cannot find settings.json\n");
	exit();
}
$query = "";
$interval = 0;
if(count($argv) > 1) {
	$query = $argv[1];
}
if(count($argv) > 2) {
	$interval = (int) $argv[2];
}

if(strlen($query) == 0) {
	fwrite(STDERR, "Usage: search [query] ([interval])\n");
	exit();
}

$config = json_decode(file_get_contents($configfile), true);
@$config_conn = $config['connection'];
@$config_tables = $config['tables'];

@$dbhost = "" . $config_conn['host'];
@$dbuser = "" . $config_conn['username'];
@$dbpass = "" . $config_conn['password'];
@$database = "" . $config_conn['database'];

@$table_tweets = "" . $config_tables['tweets'];
@$table_users = "" . $config_tables['users'];
@$table_replies = "" . $config_tables['replies'];

$link = mysql_pconnect($dbhost, $dbuser, $dbpass) or die("Could not connect");
mysql_select_db($database) or die("Could not select database");

if($interval > 0) {

	do {
		$hits = twitterSearch($query, $table_tweets, $table_users, $table_replies);
		sleep($interval);
	} while(true);
}

$hits = twitterSearch($query, $table_tweets, $table_users, $table_replies);

print(count($hits) . " results found\n");
